#!/usr/bin/env node
/**
 * Keep the shell scripts embedded in the DOM Cloud deployment YAMLs identical
 * to the .sh files in this directory.
 *
 * WHY THEY ARE EMBEDDED AT ALL. The PocketBase site has no delivery path for a
 * file. push-build.ps1 ships start-app.sh to the *app* site over SSH, but the
 * PocketBase site is created from a deployment script pasted into a dashboard
 * and nothing else — the repo is private, so DOM Cloud's `source:` git clone is
 * not an option either. Both PocketBase variants invoke a script
 * (`app_start_command: bash ./pb-start.sh`, `bash ~/public_html/pb-run.sh`)
 * that, before this, nothing ever put on the host. The site would deploy, and
 * then fail to start, with the ledger already migrated.
 *
 * Ordering is the reason for embedding rather than adding a second push script:
 * the deploy script runs on the host at deploy time, before an scp could have
 * happened. A file the deployment writes itself has no such window.
 *
 * WHY THIS GENERATOR EXISTS. Embedding duplicates the script, and a stale copy
 * here is not a cosmetic defect: pb-run.sh is what passes --encryptionEnv, and
 * a PocketBase started without the key does not degrade, it refuses to start.
 * So the .sh file is the single source and the YAML block is derived from it.
 *
 *   node sync-embeds.mjs           rewrite the YAML blocks from the .sh files
 *   node sync-embeds.mjs --check   exit 1 if any block is out of date
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const check = process.argv.includes("--check");

/** Each YAML gets the scripts it actually invokes — no more. */
const EMBEDS = [
  { yaml: "pb.deploy.yml", script: "pb-start.sh", dest: "~/public_html/pb-start.sh" },
  { yaml: "pb.deploy.kit.yml", script: "pb-run.sh", dest: "~/public_html/pb-run.sh" },
];

/**
 * A quoted heredoc (<<'EOF'), because every one of these scripts contains
 * $HOME, ${PORT:-8090} and $(dirname "$0") that must reach the file intact
 * rather than being expanded by the shell that writes it.
 */
function block(script, dest, body) {
  const tag = `HM_${script.replace(/[^a-z]+/gi, "_").toUpperCase()}`;
  const lines = body.replace(/\r\n/g, "\n").replace(/\n+$/, "").split("\n");
  return [
    `  # >>> embedded ${script} — generated by sync-embeds.mjs; edit ${script}, not this.`,
    `  - |`,
    `    cat > ${dest} <<'${tag}'`,
    ...lines.map((l) => (l.length ? `    ${l}` : "")),
    `    ${tag}`,
    `    chmod +x ${dest}`,
    `  # <<< end embedded ${script}`,
  ].join("\n");
}

let stale = 0;
for (const { yaml, script, dest } of EMBEDS) {
  const yamlPath = join(here, yaml);
  const original = readFileSync(yamlPath, "utf8");
  const body = readFileSync(join(here, script), "utf8");

  const start = `  # >>> embedded ${script}`;
  const end = `  # <<< end embedded ${script}`;
  const i = original.indexOf(start);
  const j = original.indexOf(end);
  if (i === -1 || j === -1) {
    console.error(`✗ ${yaml}: no marker pair for ${script}. Add:\n${start} …\n${end}`);
    process.exit(2);
  }

  const next = original.slice(0, i) + block(script, dest, body) + original.slice(j + end.length);
  if (next === original) {
    console.log(`  ok   ${yaml} ← ${script}`);
    continue;
  }
  stale++;
  if (check) {
    console.error(`✗ ${yaml} is out of date with ${script}`);
  } else {
    writeFileSync(yamlPath, next);
    console.log(`  ↻ updated ${yaml} ← ${script}`);
  }
}

if (check && stale) {
  console.error(`\n${stale} embedded script(s) stale. Run: node deploy/domcloud/sync-embeds.mjs`);
  process.exit(1);
}
console.log(check ? "\nEmbedded deploy scripts are in sync." : "\nDone.");
