// PDF text extraction, for credit-card and bank statements.
//
// Why the text layer and not OCR: a statement PDF generated by a bank already
// contains the exact characters — "1,234.56" is stored as those glyphs, not as
// a picture of them. Reading that layer gives arithmetically exact amounts. OCR
// on the same page can turn an 8 into a 3, and a wrong ringgit figure that a
// user trusts is far worse than a row they had to type themselves. So: text
// layer first, always, and vision only when there genuinely isn't one.
//
// Malaysian bank statements are usually password-protected (typically the IC
// number or date of birth), so a wrong/missing password is an expected outcome
// with its own answer, not a crash.
//
// Server-only. Node runtime — pdfjs runs here without a worker.

export class PdfPasswordError extends Error {
  readonly needsPassword: boolean;

  constructor(needsPassword: boolean) {
    super(needsPassword ? "This PDF is password-protected." : "That password didn't open the PDF.");
    this.needsPassword = needsPassword;
  }
}

export interface PdfText {
  pages: string[];
  text: string;
  pageCount: number;
  /** No usable text layer — the PDF is a scan, and only vision can read it. */
  scanned: boolean;
}

// A statement page is dense: hundreds of characters even on a light month. A
// page carrying only a handful is a scan with an incidental text stamp on it
// (a "CONFIDENTIAL" watermark, a page number), not a readable statement.
const MIN_CHARS_PER_PAGE = 120;

export async function extractPdfText(data: Uint8Array, password?: string): Promise<PdfText> {
  // pdfjs mutates the buffer it is handed and leaves it detached, which breaks
  // the caller if it wants the same bytes again for the vision fallback.
  const bytes = new Uint8Array(data);

  const pdfjs = await import("pdfjs-dist/legacy/build/pdf.mjs");

  let doc;
  try {
    doc = await pdfjs.getDocument({
      data: bytes,
      password: password ?? "",
      isEvalSupported: false, // no dynamic code from an untrusted file
      useSystemFonts: false,
      // We only ever read characters — never render — so skip all the font and
      // image machinery that would otherwise need a canvas in Node.
      disableFontFace: true,
    }).promise;
  } catch (err) {
    const name = (err as { name?: string })?.name;
    if (name === "PasswordException") {
      // code 1 = a password is needed; code 2 = the one we gave is wrong.
      const code = (err as { code?: number })?.code;
      throw new PdfPasswordError(code !== 2);
    }
    throw new Error(
      `That PDF couldn't be opened: ${err instanceof Error ? err.message : "unknown error"}`,
    );
  }

  const pageCount = doc.numPages;

  const pages: string[] = [];
  for (let i = 1; i <= pageCount; i++) {
    const page = await doc.getPage(i);
    const content = await page.getTextContent();

    // A statement is a table, and a table read as a flat character stream is
    // gibberish: the date, the description and the amount of one row end up in
    // three different places. pdfjs gives every item a transform matrix, so
    // group by baseline (y) to rebuild rows, then order by x within each row.
    const items = content.items as Array<{ str: string; transform: number[] }>;
    const rows = new Map<number, { x: number; str: string }[]>();

    for (const it of items) {
      if (!it.str) continue;
      const x = it.transform[4];
      const y = Math.round(it.transform[5]); // 1pt buckets — same line, same key
      const row = rows.get(y) ?? [];
      row.push({ x, str: it.str });
      rows.set(y, row);
    }

    const lines = [...rows.entries()]
      .sort((a, b) => b[0] - a[0]) // PDF y grows upward; the page reads downward
      .map(([, row]) =>
        row
          .sort((a, b) => a.x - b.x)
          .map((c) => c.str)
          .join(" ")
          .replace(/\s+/g, " ")
          .trim(),
      )
      .filter(Boolean);

    pages.push(lines.join("\n"));
    page.cleanup();
  }

  await doc.destroy();

  const text = pages.join("\n\n");
  const avgChars = pages.length ? text.length / pages.length : 0;

  return {
    pages,
    text,
    pageCount,
    scanned: avgChars < MIN_CHARS_PER_PAGE,
  };
}
