// PocketBase client via REST (fetch) — no SDK dependency, mirrors the style
// of gemini.ts. The Next.js server authenticates as a PocketBase superuser;
// collections are never exposed directly to browsers (all API rules are
// superuser-only). Server-side only — never import from a "use client" module.

import { config, isPocketBaseConfigured } from "./config";

interface PBListResult<T> {
  items: T[];
  totalItems: number;
}

let cachedToken: { token: string; expiresAt: number } | null = null;

async function getToken(): Promise<string> {
  if (!isPocketBaseConfigured()) {
    throw new Error(
      "PocketBase is not configured. Set POCKETBASE_URL, POCKETBASE_ADMIN_EMAIL, POCKETBASE_ADMIN_PASSWORD.",
    );
  }
  // superuser tokens last ~2 weeks; refresh well before that
  if (cachedToken && Date.now() < cachedToken.expiresAt) return cachedToken.token;

  const res = await fetch(
    `${config.pocketbaseUrl}/api/collections/_superusers/auth-with-password`,
    {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        identity: config.pocketbaseAdminEmail,
        password: config.pocketbaseAdminPassword,
      }),
      cache: "no-store",
    },
  );
  if (!res.ok) {
    throw new Error(`PocketBase auth failed (${res.status}) — is it running? Try: npm run pb:start`);
  }
  const data = await res.json();
  cachedToken = { token: data.token, expiresAt: Date.now() + 6 * 60 * 60 * 1000 };
  return data.token;
}

async function pbFetch<T>(path: string, init?: RequestInit): Promise<T> {
  const token = await getToken();
  const res = await fetch(`${config.pocketbaseUrl}${path}`, {
    ...init,
    headers: {
      Authorization: token,
      "Content-Type": "application/json",
      ...(init?.headers ?? {}),
    },
    cache: "no-store",
  });
  if (!res.ok) {
    const detail = await res.text();
    throw new Error(`PocketBase ${res.status} on ${path}: ${detail.slice(0, 300)}`);
  }
  // DELETE and some writes return 204 No Content — nothing to parse.
  if (res.status === 204) return undefined as T;
  return res.json() as Promise<T>;
}

// List records with a PocketBase filter expression.
export async function pbList<T>(
  collection: string,
  opts: { filter?: string; sort?: string; expand?: string; perPage?: number } = {},
): Promise<T[]> {
  const params = new URLSearchParams({ perPage: String(opts.perPage ?? 500), skipTotal: "1" });
  if (opts.filter) params.set("filter", opts.filter);
  if (opts.sort) params.set("sort", opts.sort);
  if (opts.expand) params.set("expand", opts.expand);
  const data = await pbFetch<PBListResult<T>>(
    `/api/collections/${collection}/records?${params.toString()}`,
  );
  return data.items;
}

export async function pbFirst<T>(
  collection: string,
  filter: string,
  opts: { sort?: string } = {},
): Promise<T | null> {
  const items = await pbList<T>(collection, { filter, sort: opts.sort, perPage: 1 });
  return items[0] ?? null;
}

export async function pbCreate<T>(
  collection: string,
  body: Record<string, unknown>,
): Promise<T> {
  return pbFetch<T>(`/api/collections/${collection}/records`, {
    method: "POST",
    body: JSON.stringify(body),
  });
}

export async function pbUpdate<T>(
  collection: string,
  id: string,
  body: Record<string, unknown>,
): Promise<T> {
  return pbFetch<T>(`/api/collections/${collection}/records/${id}`, {
    method: "PATCH",
    body: JSON.stringify(body),
  });
}

export async function pbDelete(collection: string, id: string): Promise<void> {
  await pbFetch<unknown>(`/api/collections/${collection}/records/${id}`, {
    method: "DELETE",
  });
}

// ── files ──────────────────────────────────────────────────────────────────
//
// Attachments go up as multipart, which is the one place the JSON Content-Type
// above must NOT be set: the boundary is generated by fetch when it serialises
// the FormData, and naming the type by hand produces a body the server cannot
// parse. Hence a separate path rather than a flag on pbFetch.

/** Append files to a record's file field. Returns the record's stored filenames. */
export async function pbUploadFiles(
  collection: string,
  id: string,
  field: string,
  files: { name: string; type: string; bytes: Uint8Array }[],
): Promise<string[]> {
  if (!files.length) return [];
  const token = await getToken();
  const form = new FormData();
  for (const f of files) {
    // "+" prefix appends instead of replacing, so uploading a second photo to a
    // record does not silently discard the first.
    form.append(`+${field}`, new Blob([f.bytes as unknown as BlobPart], { type: f.type }), f.name);
  }
  const res = await fetch(`${config.pocketbaseUrl}/api/collections/${collection}/records/${id}`, {
    method: "PATCH",
    headers: { Authorization: token },
    body: form,
    cache: "no-store",
  });
  if (!res.ok) {
    const detail = await res.text();
    throw new Error(`PocketBase ${res.status} uploading to ${collection}/${id}: ${detail.slice(0, 300)}`);
  }
  const rec = (await res.json()) as Record<string, unknown>;
  const stored = rec[field];
  return Array.isArray(stored) ? (stored as string[]) : stored ? [String(stored)] : [];
}

/**
 * Stream one stored file back. The caller is responsible for having checked that
 * this user may see the record — this function only knows how to fetch bytes.
 *
 * `transactions` is superuser-only, so its files are not reachable by URL from a
 * browser; the superuser token is what opens them, and it never leaves the
 * server. `thumb` is passed straight to PocketBase, which generates and caches
 * the resize itself — the brief is explicit that thumbnails are not made
 * client-side.
 */
export async function pbFileResponse(
  collection: string,
  recordId: string,
  filename: string,
  opts: { thumb?: string } = {},
): Promise<Response> {
  const token = await getToken();
  const params = new URLSearchParams();
  if (opts.thumb) params.set("thumb", opts.thumb);
  const qs = params.toString();
  return fetch(
    `${config.pocketbaseUrl}/api/files/${collection}/${encodeURIComponent(recordId)}/${encodeURIComponent(filename)}${qs ? `?${qs}` : ""}`,
    { headers: { Authorization: token }, cache: "no-store" },
  );
}

// Escape a value for use inside a PocketBase filter string literal.
export function pbStr(value: string): string {
  return `'${value.replace(/'/g, "\\'")}'`;
}
