import type { MetadataRoute } from "next";

// PWA manifest — makes HoneyMoney installable ("Add to Home Screen") on mobile
// WITHOUT ever forcing it. It works as a normal browser page; installing is a
// user choice. No service worker (avoids stale-cache surprises in the demo).
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "HoneyMoney — AI Financial Wellness",
    short_name: "HoneyMoney",
    description: "Funding transparency, spending autonomy — a knowledge-graph money app for personal, family & business.",
    start_url: "/",
    display: "standalone",
    orientation: "portrait",
    background_color: "#ffffff",
    theme_color: "#FF7518",
    // PNGs, not the SVG: a maskable icon is cropped to the launcher's shape and
    // needs an opaque full-bleed plate behind the mark — a transparent SVG got
    // its rays clipped against nothing. Generated by `npm run icons`.
    icons: [
      { src: "/icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
      { src: "/icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
      { src: "/icon-maskable.png", sizes: "512x512", type: "image/png", purpose: "maskable" },
    ],
  };
}
